# Generated by Django 2.2.3 on 2020-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Barrister', 'Barrister')], default='User', max_length=32),
        ),
    ]
