# Generated by Django 2.2.3 on 2020-03-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200329_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Role'),
        ),
    ]
