# Generated by Django 2.2.3 on 2020-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200331_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contacts',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
