# Generated by Django 2.2.3 on 2020-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EducationAndWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('from_time', models.DateField(auto_now_add=True)),
                ('to_time', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.ManyToManyField(to='account.Award'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experiences',
            field=models.ManyToManyField(to='account.EducationAndWorkExperience'),
        ),
    ]
