# Generated by Django 2.2.3 on 2020-04-01 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200401_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=2014),
            preserve_default=False,
        ),
    ]
