# Generated by Django 2.2.3 on 2020-04-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200401_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
