# Generated by Django 2.2.3 on 2020-04-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200402_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationandworkexperience',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
            preserve_default=False,
        ),
    ]
