# Generated by Django 3.0.3 on 2020-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200402_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idcard_fin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idcard_serial_num',
            field=models.SmallIntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.SmallIntegerField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
