# Generated by Django 2.2.3 on 2020-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200403_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='idcard_fin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='idcard_serial_num',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fin',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_prefix',
            field=models.CharField(choices=[('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seriya',
            field=models.SmallIntegerField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.SmallIntegerField(max_length=12, null=True, unique=True),
        ),
    ]
