# Generated by Django 3.0.3 on 2020-04-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200403_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idcard_serial_num',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
