# Generated by Django 2.2.3 on 2020-04-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200404_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='seriya',
            field=models.IntegerField(max_length=20, null=True, unique=True),
        ),
    ]
