# Generated by Django 2.2.3 on 2020-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200404_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='seriya',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
