# Generated by Django 2.2.3 on 2020-04-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_customuser_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adress',
            new_name='address',
        ),
    ]
