# Generated by Django 3.0.3 on 2020-04-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200404_1357'),
        ('account', '0024_auto_20200404_1604'),
    ]

    operations = [
    ]
