# Generated by Django 2.2.3 on 2020-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20200417_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_summary',
            field=models.CharField(max_length=2014, null=True),
        ),
    ]
