# Generated by Django 2.2.3 on 2020-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200417_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationandworkexperience',
            name='start',
            field=models.DateField(),
        ),
    ]
