# Generated by Django 2.2.3 on 2020-11-02 08:07

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201031_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to=chat.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='chat.Message'),
        ),
    ]
