# Generated by Django 3.0.3 on 2020-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20201112_1155'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_barrist_261b89_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['barrister', 'email'], name='clients_cli_barrist_c2afda_idx'),
        ),
    ]
