# Generated by Django 3.0.3 on 2020-11-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20201117_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='clients.Case'),
        ),
    ]
