# Generated by Django 3.0.3 on 2020-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20201117_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Bağlı', 'Bağlı'), ('Uğurlu', 'Uğurlu'), ('Davam edir', 'Davam edir')], default='Status yoxdur', max_length=30),
        ),
    ]
