# Generated by Django 3.0.3 on 2020-11-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Bağlı', 'Bağlı'), ('Uğurlu', 'Uğurlu'), ('Davam edir', 'Davam edir')], default='Bağlı', max_length=30),
        ),
    ]
