# Generated by Django 3.0.3 on 2020-11-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20201124_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.Case'),
        ),
    ]
