# Generated by Django 3.0.3 on 2020-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_notes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['date'], name='clients_not_date_0ecee1_idx'),
        ),
    ]
