# Generated by Django 3.0.3 on 2020-12-03 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientnotes', to='clients.Client'),
            preserve_default=False,
        ),
    ]
