# Generated by Django 2.2.3 on 2020-03-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('from_time', models.TimeField(auto_now=True)),
                ('to_time', models.TimeField(auto_now=True)),
                ('remind_me', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TaskCategory')),
            ],
        ),
    ]
