# Generated by Django 2.2.3 on 2020-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200328_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remind_me',
            field=models.DateTimeField(null=True),
        ),
    ]
