# Generated by Django 2.2.3 on 2020-04-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_occurrence_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='to_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='from_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_all_day',
        ),
        migrations.AddField(
            model_name='event',
            name='rule',
            field=models.ForeignKey(blank=True, help_text="Select '----' for a one time only event.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Rule', verbose_name='rule'),
        ),
    ]
