# Generated by Django 2.2.3 on 2020-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['publication', 'date'], name='home_commen_publica_fad0cc_idx'),
        ),
    ]
