# Generated by Django 2.2.3 on 2020-04-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200417_1337'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'category', 'start', 'end'], name='home_event_user_id_9ce582_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['name'], name='home_eventc_name_63302d_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['date'], name='home_news_date_cdc176_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='home_news_slug_2cb4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['user', 'date'], name='home_public_user_id_b20d58_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['date'], name='home_public_date_4b0200_idx'),
        ),
    ]
