# Generated by Django 3.0.3 on 2020-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200401_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
    ]
