# Generated by Django 2.2.3 on 2020-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200417_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(upload_to='publication'),
        ),
    ]
