# Generated by Django 2.2.3 on 2020-04-21 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('in progress', 'in progress')], default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
