# Generated by Django 2.2.3 on 2020-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200503_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='title',
            new_name='country',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
