# Generated by Django 3.0.3 on 2020-05-03 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200503_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='file',
            new_name='fayl',
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
