# Generated by Django 2.2.3 on 2020-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='task'),
        ),
    ]
