# Generated by Django 2.2.3 on 2020-05-20 13:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_contact_musteri'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('Inbox', 'Inbox'), ('Draft', 'Draft'), ('Delted', 'Deleted')], max_length=64)),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=128, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content')),
                ('flag', models.CharField(choices=[('Answered', 'Answered'), ('Flagged', 'Flagged'), ('Draft', 'Draft'), ('Deleted', 'Deleted'), ('Seen', 'Seen'), ('$Forwarded', '$Forwarded'), ('$NotPhishing', '$NotPhishing'), ('$label1', '$label1'), ('$label2', '$label2'), ('$label3', '$label3'), ('$label4', '$label4'), ('$label5', '$label5'), ('Junk', 'Junk'), ('NotJunk', 'NotJund')], max_length=64)),
                ('num', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='attachment')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='home.Email')),
            ],
        ),
    ]
