# Generated by Django 2.2.3 on 2020-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_attachment_email_emailaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
