# Generated by Django 3.0.3 on 2020-07-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200522_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='home.Email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Draft', 'Draft'), ('Sent', 'Sent'), ('Deleted', 'Deleted')], max_length=64),
        ),
    ]
