# Generated by Django 3.0.3 on 2020-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200713_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
