# Generated by Django 2.2.3 on 2020-08-27 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_emailaccount_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musteri',
            new_name='Client',
        ),
    ]
