# Generated by Django 2.2.3 on 2020-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200901_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
