# Generated by Django 2.2.3 on 2020-09-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_eventcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='color',
            field=models.CharField(default='#ffff00', max_length=16),
            preserve_default=False,
        ),
    ]
