# Generated by Django 2.2.3 on 2020-09-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_eventcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remind_me',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
