# Generated by Django 2.2.3 on 2020-09-07 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200902_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='flag',
            field=models.CharField(choices=[('Answered', 'Answered'), ('Flagged', 'Flagged'), ('Drafts', 'Drafts'), ('Deleted', 'Deleted'), ('Seen', 'Seen'), ('$Forwarded', '$Forwarded'), ('$NotPhishing', '$NotPhishing'), ('$label1', '$label1'), ('$label2', '$label2'), ('$label3', '$label3'), ('$label4', '$label4'), ('$label5', '$label5'), ('Junk', 'Junk'), ('NotJunk', 'NotJund')], max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Drafts', 'Drafts'), ('Sent', 'Sent'), ('Deleted', 'Deleted')], max_length=64),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='event-categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
