# Generated by Django 2.2.3 on 2020-09-07 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20200907_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='text_color',
            field=models.CharField(default="#fff000", max_length=16),
            preserve_default=False,
        ),
    ]
