# Generated by Django 2.2.3 on 2020-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20200907_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
