# Generated by Django 2.2.3 on 2020-09-07 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200907_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='appointmentstatus',
            index=models.Index(fields=['name'], name='home_appoin_name_2e2578_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.AppointmentStatus'),
            preserve_default=False,
        ),
    ]
