# Generated by Django 2.2.3 on 2020-09-09 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200907_1729'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='home_appoin_user_id_ca5087_idx',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='country',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('not arrived', 'not arrived'), ('arrived', 'arrived')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'date', 'time'], name='home_appoin_user_id_ff5188_idx'),
        ),
        migrations.DeleteModel(
            name='AppointmentStatus',
        ),
    ]
