# Generated by Django 3.0.3 on 2020-09-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200909_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='password',
        ),
    ]
