# Generated by Django 2.2.3 on 2020-09-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20200909_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Contact'),
        ),
    ]
