# Generated by Django 2.2.3 on 2020-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20200909_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remind_me',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
