# Generated by Django 2.2.3 on 2020-09-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_appointment_remind_me'),
        ('home', '0035_remove_emailaccount_password'),
    ]

    operations = [
    ]
