# Generated by Django 2.2.3 on 2020-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_merge_20200917_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Drafts', 'Drafts'), ('Sent', 'Sent'), ('Trash', 'Trash')], max_length=64),
        ),
    ]
