# Generated by Django 3.0.3 on 2020-10-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20201022_1604'),
        ('home', '0043_receiver'),
    ]

    operations = [
    ]
