# Generated by Django 2.2.3 on 2020-10-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_merge_20201026_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='flag',
            field=models.CharField(choices=[('Answered', 'Answered'), ('Flagged', 'Flagged'), ('Drafts', 'Drafts'), ('Deleted', 'Deleted'), ('Seen', 'Seen'), ('Unseen', 'Unseen'), ('$Forwarded', '$Forwarded'), ('$NotPhishing', '$NotPhishing'), ('$label1', '$label1'), ('$label2', '$label2'), ('$label3', '$label3'), ('$label4', '$label4'), ('$label5', '$label5'), ('Junk', 'Junk'), ('NotJunk', 'NotJund')], max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Drafts', 'Drafts'), ('Sent', 'Sent'), ('Trash', 'Trash'), ('Spam', 'Spam')], max_length=64),
        ),
    ]
