# Generated by Django 3.0.3 on 2020-10-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0044_merge_20201026_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='flag',
            field=models.CharField(choices=[('Answered', 'Answered'), ('Flagged', 'Flagged'), ('Drafts', 'Drafts'), ('Deleted', 'Deleted'), ('Seen', 'Seen'), ('Unseen', 'Unseen'), ('$Forwarded', '$Forwarded'), ('$NotPhishing', '$NotPhishing'), ('$label1', '$label1'), ('$label2', '$label2'), ('$label3', '$label3'), ('$label4', '$label4'), ('$label5', '$label5'), ('Junk', 'Junk'), ('NotJunk', 'NotJund')], max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('Inbox', 'Inbox'), ('Drafts', 'Drafts'), ('Sent', 'Sent'), ('Trash', 'Trash'), ('Spam', 'Spam')], max_length=64),
        ),
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
