# Generated by Django 2.2.3 on 2020-10-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20201028_1631'),
        ('home', '0045_auto_20201029_1311'),
    ]

    operations = [
    ]
