# Generated by Django 3.0.3 on 2020-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20201202_1149'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='home_contac_user_id_970c0e_idx',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'first_name', 'last_name'], name='home_contac_user_id_1bc44e_idx'),
        ),
    ]
