# Generated by Django 3.0.3 on 2020-12-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20201202_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='home.Contact'),
        ),
    ]
