# Generated by Django 2.2.3 on 2020-04-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('rgb', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['name'], name='shop_color_name_f4c71c_idx'),
        ),
    ]
