# Generated by Django 2.2.3 on 2020-09-24 11:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('header', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('footer', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='LawAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LawType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('number', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='laws.Chapter')),
            ],
        ),
        migrations.AddIndex(
            model_name='lawtype',
            index=models.Index(fields=['name'], name='laws_lawtyp_name_1fec6e_idx'),
        ),
        migrations.AddIndex(
            model_name='lawagency',
            index=models.Index(fields=['name'], name='laws_lawage_name_af4c58_idx'),
        ),
        migrations.AddField(
            model_name='division',
            name='law',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='laws.Law'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='laws.Division'),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['chapter', 'name'], name='laws_matter_chapter_5439e8_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['law', 'name'], name='laws_divisi_law_id_c8d835_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['law', 'number'], name='laws_divisi_law_id_e8326c_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['division', 'name'], name='laws_chapte_divisio_860853_idx'),
        ),
    ]
