# Generated by Django 2.2.3 on 2020-09-28 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_auto_20200924_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='laws.LawAgency'),
            preserve_default=False,
        ),
    ]
